"""add_inference_catalog_and_shadow_evaluations

Revision ID: 373526e19799
Revises: 4b5d729830cf
Create Date: 2026-03-25 19:43:44.149660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373526e19799'
down_revision: Union[str, None] = '4b5d729830cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
